var a = prompt("Введіть перший коефіцієнт:");
var b = prompt("Введіть другий коефіцієнт:");
var c = prompt("Введіть третій коефіцієнт:");
var x1, x2,d;
d = b * b - 4 * a * c;
x1 = (-b - Math.sqrt(d)) / (2 * a);
x2 = (-b + Math.sqrt(d)) / (2 * a);
alert('D = ' + d);
alert('x1 = ' + x1);
alert('x2 = ' + x2);
